compatibility_date = "2022-12-31"
name = "gh-download"
account_id = "5a007c3f1b1463e3f024ef2a654e3307"
routes = [
    { pattern = "gh.seby.io/*", zone_name = "seby.io" },
    { pattern = "gh.seby.au/*", zone_name = "seby.au" }
]
main = "index.js"
