compatibility_date = "2022-10-02"
name = "raffle"
account_id = "5a007c3f1b1463e3f024ef2a654e3307"
# workers_dev = true
routes = [
    { pattern = "raffle.seby.io", zone_name = "seby.io" },
    { pattern = "raffle.seby.au", zone_name = "seby.au" }
]
main = "index.js"
